### ISSUE TITLE
getting "Cannot have two HTML5 backends at the same time" error on react 18

### ISSUE THREAD

**Issue by gayathrig321** [Kiho/react-form-builder#220] opened 2022-09-29 15:25 UTC
Getting below issue after upgrading to react 18. Could you please guide me on this.

Uncaught Error: Cannot have two HTML5 backends at the same time.
    at HTML5BackendImpl.setup (HTML5BackendImpl.js:403:1)
    at DragDropManagerImpl.handleRefCountChange (DragDropManagerImpl.js:38:1)
    at Object.dispatch (redux.js:297:1)
    at HandlerRegistryImpl.addSource (HandlerRegistryImpl.js:92:1)
    at registerSource (registration.js:10:1)
    at DragDropContainer.receiveType (decorateHandler.js:151:1)
    at DragDropContainer.receiveProps (decorateHandler.js:136:1)
    at DragDropContainer.componentDidMount (decorateHandler.js:112:1)
    at commitLayoutEffectOnFiber (react-dom.development.js:23305:1)
    at commitLayoutMountEffects_complete (react-dom.development.js:24688:1)

**Comment by Kiho** [comment] 2022-10-02 03:58
Maybe you can try delete yarn.lock & node_modules then reinstall.
I have 2 examples here https://github.com/Kiho/react-form-builder/blob/master/examples/next/package.json & https://github.com/Kiho/react-form-builder/blob/master/examples/demo/package.json running without issues.

**Comment by seiyaterada** [comment] 2022-10-07 06:40
@gayathrig321 I'm also having the exact same problem, were you able to find a solution?

**Comment by farid-ansari** [comment] 2022-10-07 12:41
Anyone having a problem with this, try this:

1. First, install react-dnd, react-dnd-html5-backend in your project with 11.1.3 version
2. Go to your entrypoint file (probably `index.js`), and make a global dnd context as below:

```js
const GlobalDndContext = (props) => {
    return (
        <DndProvider backend={HTML5Backend} key={1}>
            {props.children}
        </DndProvider>
    );
};
```
3. Finally wrap your main <App /> around it:

```js
root.render(
    <React.StrictMode>
          <GlobalDndContext>
              <App />
          </GlobalDndContext>
    </React.StrictMode>
);
```

That should fix the issue. I tried many other approaches, but this is the one that worked.

**Comment by ljorgens** [comment] 2023-04-16 21:20
Nothing worked for me, had to downgrade react/react dom to 17.

Made minimum viable project to show the error here: https://github.com/ljorgens/react-form-builder2-problem-repo

Steps to reproduce:

1. yarn install
2. yarn start
*Should successfully start the app
3. Add header text to form
4. Click edit form button
5. Dismiss edit form screen
6. Add another header text to form
*Should throw the error

**Comment by Kiho** [comment] 2023-04-26 03:59
@ljorgens I don't why it is not workin with CRA.
However, I check with this sample app https://github.com/Kiho/react-form-builder/blob/master/examples/demo/package.json
and it does not throwing a error.

**Comment by ljorgens** [comment] 2023-08-07 01:08
This seems to be resolved in the current version and can be closed

**Closed** 2023-08-08 23:36 UTC
